# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f160a8d12fc3cbc7f164b390f6611b399bfba80c4bb167716c4d3a16d2cf81fd04030320442c5f3fecb24dd5dec70ec1b8fc4b93cb21fb2e155a5ff3fd0081b

test:
  secret_key_base: 44b2c10c15ed949ad554cb98ce57de2e7fd799a66c347932c12b2e13c954e9f171410829254b0605e6d569dee61c2930f218e550f0d6d6d33c97ddadd93adab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
